### PR TITLE
Fixes Gdebi issue and restore issue too

### LINKED ISSUE #140: GDebi Package Installer is in csv but not applied
Although gdebi is in the csv it is not applied

Filename : gdebi.desktop

content of file

[Desktop Entry]
Name=GDebi Package Installer
GenericName=Package Installer
Comment=Install and view software packages
Exec=gdebi-gtk %f
Icon=gnome-mime-application-x-deb
Terminal=false
Type=Application
Categories=System;
MimeType=application/x-deb;application/x-debian-package;
NotShowIn=KDE;
X-Ubuntu-Gettext-Domain=gdebi
StartupNotify=true
Keywords=package;apt;dpkg;install

Working on linux mint 17.2 clean install

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This will fix #140 #150 #129

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
The issue was you were looking if the current icon exists before doing the changes, we all know that gdebi for example does not have a hardcoded icon but a wrong one and it's not a path so the icon was not found by the script and so the hardcoded icon was not fixed. What i've done now, is that if the icon do exists copy the icon to hicolor scalable if it's an svg icon, if it's png or xpm icon copy it to 48x48 size. And the same thing when you revert, i just remove the icons from both folder scalablee & 48x48

**Comment by bil-elmoussaoui** [comment]
This will fix #145 too

**Comment by bil-elmoussaoui** [comment]
This fixes #128 #149 and the hardcoded applications can have "hardcoded" instead of the current icon name

**Comment by Foggalong** [comment]
Because there's so much in this one commit it's gonna take a bit of testing to analyse. As a first point though, I think `n/a` can be replaced with `hardcoded` [on this line](https://github.com/Foggalong/hardcode-fixer/pull/151/files#diff-25191428d2e7f19ac68b790898a2b68eR42) too.

**Comment by bil-elmoussaoui** [comment]
i will take a look on that later ;) i didnt add jetbrains ide to the database file too, i will do that today

**Comment by Foggalong** [comment]
:+1:

**Comment by bil-elmoussaoui** [comment]
@Foggalong Can you tell me the line number ?

**Comment by Foggalong** [comment]
Sorry, thought that was what I'd linked to! My bad - [here it is](https://github.com/Foggalong/hardcode-fixer/blob/master/tofix.csv#L42)

**Comment by bil-elmoussaoui** [comment]
Done, i added Jetbrains desktop files too. Some of the desktop files do exists but with a different file name; i think jetbrains changed the desktop file names in the latest releases ;) Everything works fine now

**Comment by Foggalong** [comment]
Yeah, some of the more annoying software releases a new .desktop file name with each version

**Comment by bil-elmoussaoui** [comment]
All we can do is keep updating the database file! Hope that one day all of that will get fixed

**Comment by Foggalong** [comment]
Yeah :)

**Comment by vs0uz4** [comment]
thank you, I'll do a "git pull" now!

**Pull request merged**
