### PR TITLE
Fix hardcoded apps

### LINKED ISSUE #149: Php Storm icon not fixed
after running sudo command ./fix.sh the same fixed several icons, with the exception of PhpStorm icon.

vs0uz4@vs0uz4-NTB:~/Code/hardcode-fixer$ sudo ./fix.sh 
G: Fixing HP Printer...
G: Fixing Intel Graphics Installer...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...
G: Fixing Slingscold...
G: Fixing Valentina Studio...
G: Fixing YouTubeDL GUI...

result:
captura de tela de 2015-08-17 10 43 57

how to solve?

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Fix #149 
While checking hardcoded apps,and detecting the new icons the script will add automatically to a new csv file and use it when reverting to be sure that's the right file! 
This will need some testing, if you find any issue i will fix it ;)

### CODE REVIEW

**Comment by krzysieki** [comment]
Thanks I confirm that this fixes #210 with no problems

**Comment by bil-elmoussaoui** [comment]
@krzysieki Can you try to restore and see if old icon will be shown? or changing the theme to an other one and see if everything works fine in your case

**Comment by krzysieki** [comment]
I called command to revert: "fix.sh -r" but the old icon didn't show. And in ~/.local/share/applications/jetbrains-idea.desktop file there is a line "Icon=hardcoded".

**Comment by bil-elmoussaoui** [comment]
In the same folder where you have the script. Is there any new csv file ? If so can you paste it here so i can see what's the problem:)

**Comment by bil-elmoussaoui** [comment]
Should be fixed now :+1:

**Comment by krzysieki** [comment]
Thanks for patch. "fix.sh -r" works now :)

Don't know If it is still needed, but the new csv file's content is:

```
Intellij IDE,jetbrains-idea,hardcoded,/home/krzysiek/.local/share/umake/ide/idea-ultimate/bin/idea.png,/home/krzysiek/.local/share/applications/
Visual Studio,visual-studio-code,hardcoded,/home/krzysiek/.local/share/umake/web/visual-studio-code/resources/app/resources/linux/vscode.png,/home/krzysiek/.local/share/applications/
Intellij IDE,jetbrains-idea,hardcoded,/home/krzysiek/.local/share/umake/ide/idea-ultimate/bin/idea.png,/home/krzysiek/.local/share/applications/
Visual Studio,visual-studio-code,hardcoded,/home/krzysiek/.local/share/umake/web/visual-studio-code/resources/app/resources/linux/vscode.png,/home/krzysiek/.local/share/applications/
```

**Comment by bil-elmoussaoui** [comment]
@krzysieki Thanks! Can you revert again, and remove the csv file, and apply the patch again. And copy the new csv file content's :+1:

**Comment by krzysieki** [comment]
New csv file contents:
```
Intellij IDE,jetbrains-idea,hardcoded,/home/krzysiek/.local/share/umake/ide/idea-ultimate/bin/idea.png,/home/krzysiek/.local/share/applications/
Visual Studio,visual-studio-code,hardcoded,/home/krzysiek/.local/share/umake/web/visual-studio-code/resources/app/resources/linux/vscode.png,/home/krzysiek/.local/share/applications/
```

Log after calling "./fix.sh"
```
L: Fixing Aptik...
L: Fixing HP Printer...
grep: hardcoded_apps.csv: No such file or directory
L: Fixing Intellij IDE...
L: Fixing Nvidia Settings...
L: Fixing Python (v2.7)...
L: Fixing Python (v3.4)...
L: Fixing Python (v3.5)...
L: Fixing Skype...
L: Fixing Ubuntu Web Browser...
L: Fixing Visual Studio...
L: Fixing X-Diagnose...
```

**Comment by bil-elmoussaoui** [comment]
@krzysieki Thanks for testing this! Everything works fine. I pushed a new commit so you won't see this error `grep: hardcoded_apps.csv: No such file or directory` at all. What about when you change the icon theme to an other one after fixing the icons? the default icons are used?

**Comment by krzysieki** [comment]
Default icon for an unknown app is used. I assume this is correct bahavior?
screenshot from 2015-12-14 23-12-05

**Comment by bil-elmoussaoui** [comment]
@krzysieki Non, the default icons (the hardcoded ones) should be used. I forgot to copy those icons to icons folder. Should be fixed now, try to revert and apply again? :)

**Comment by bil-elmoussaoui** [comment]
@Foggalong I did a lot of improvements on this today; I moved the backup code to a function that being called (the same code to backup an icon was repeated more than 3 times in the code); Tested this on my machine today and everything works just fine :+1: Do you think you will have some free time to test this ? :)

**Pull request closed without merging**
