### PR TITLE
Correctly backup icons

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This will correctly backup existing icons so if the user changes the theme, the old icon will be used
The next PR will be the support of Hardcoded icons i hope :)

### CODE REVIEW

**Comment by Foggalong** [comment]
@bil-elmoussaoui I might be missing something, but why is there different behaviour for different image extensions?

**Comment by bil-elmoussaoui** [comment]
The svg files are copied to scalable folder which means that they can be used anywhere without having blurry icons..and the PNG, xpm are only copied to 48 size. If you want i can implement an icon size détection for non scalable icons

**Comment by Foggalong** [comment]
@bil-elmoussaoui We can probably leave out size detection for now unless not having it causes any problems.

The sticking of SVG icons in scalable isn't something I'd thought of so kudos on that. I like that you've consolidated it all into a single function too.

**Comment by bil-elmoussaoui** [comment]
À new PR is coming soon😃

**Pull request merged**
