### PR TITLE
Edit 2

### PR DESCRIPTION
**Pull request by nathaneltitane**
Fixed all apparent typos or small errors of my part from the initial edit.

Standards and practicality are different: [yY]* is to be expected as a more natural input for the choice and would be the first answer (no capital) to be taken in by user input as answer - standards don't always win, not that it changes much in this case...

get_error was an assumption of my part since you were forcing an 'exit 1' that could have been captured for error parsing - changed to general_error - omit 'function' for redundancy.

the indentation error has been fixed- overlooked

removed the added spacing atop the file- made for a more 'airy' (readable) header...

changed nvidia-settings new entry in 'tofix.csv'

added more missing braces, brackets and quotes where actually needed.

### CODE REVIEW

**Comment by Foggalong** [comment]
Typo fixes are appreciated.

The reason it's standard is because the other way around just looks weird, even though users would be more inclined to enter the lower case. If the prompt is distracting in its appearance it's not doing its job.

The error code used by `gerror` is always 1, but the user is always shown a message before it's executed explaining what went wrong. You've also changed the name of the function in the definition, but not anywhere else in the script.

It's still using 8 spaces / tabs for indentation though. Because of this it's also making it difficult to read and use the diff.

Which style is more readable depends on the user. With the inconsistent spacing between command and comment though it makes it ambiguous as to what corresponds to what.

You're also still splitting other functions into multiple lines (most noticably `if $COND; then` statements) when a single line is sufficient & readable & within the bash style guide.

**Comment by nathaneltitane** [comment]
fixed


Nathanel Titane,

*TND*esigns | Industrial + Graphic Design Solutions

BInd.D | BDInd. - Membre | ADIQ | Member

514 . 583 . 7386

*nathaneltitane.com <http://www.nathaneltitane.com> *|*
nathaneltitane.blogspot.com <http://nathaneltitane.blogspot.com>*

**Comment by Foggalong** [comment]
It still has the wrong `if` formatting though

```bash
if $CONDITION
then
    do_stuff
fi
```

rather than the more succinct

```bash
if $CONDITION; then
    do_stuff
fi
```

**Comment by Foggalong** [comment]
This still hasn't addressed most of the problems stated in my original comment :/ closing

**Pull request closed without merging**
