### PR TITLE
Fix hardcoded icons

### LINKED ISSUE #149: Php Storm icon not fixed
after running sudo command ./fix.sh the same fixed several icons, with the exception of PhpStorm icon.

vs0uz4@vs0uz4-NTB:~/Code/hardcode-fixer$ sudo ./fix.sh 
G: Fixing HP Printer...
G: Fixing Intel Graphics Installer...
G: Fixing Python (v2.7)...
G: Fixing Python (v3.4)...
G: Fixing Slingscold...
G: Fixing Valentina Studio...
G: Fixing YouTubeDL GUI...

result:
captura de tela de 2015-08-17 10 43 57

how to solve?

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This will fix hardcoded icons issue, fix #149

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
But still, forcing the user to always use the downloaded version in `/tmp/` will make reverts just impossible as the icon name will be hardcoded in the database file...

**Comment by bil-elmoussaoui** [comment]
Ok i will work on this as soon as possible, i will create a new csv file where the hardcoded icons will be stored and i will use it in reverting ;)

**Comment by Foggalong** [comment]
Adding another CSV file won't work because of the different locations checked for differen global/local locations: there'll never be a standard place to store it :(

**Comment by bil-elmoussaoui** [comment]
I will add those informations into the new csv file ;)

**Comment by bil-elmoussaoui** [comment]
I will update this as soon as i'have some free time

**Comment by Foggalong** [comment]
No rush :+1:

**Comment by bil-elmoussaoui** [comment]
I opened a new pull request!

**Pull request closed without merging**
