### PR TITLE
Updating FreeCAD icon path

### PR DESCRIPTION
**Pull request by leoheck**
The standard path is /usr/share/freecad/freecad.xpm. Actually, one can update the tool to update a list of paths if they exist.

### CODE REVIEW

**Comment by palob** [comment]
Better don't update the path but add your path. It's quite probable the old path is floating around somewhere. It differs from distro to distro and from packager to packager.

**Comment by leoheck** [comment]
I don't know how the fix.sh works. Can I duplicate the application line with another path?

**Comment by palob** [comment]
Yep, it's no problem to have multiple paths for the same application.

**Comment by Foggalong** [comment]
I'll be honest, neither the explanation of the CSV formatting in the readme nor the spacing the in the CSV file itself appeal to me as additions. Thanks, but no thanks

**Comment by leoheck** [comment]
Ok, this pull request is old and it was wrong. I will try another pull request after once I finish.

**Comment by leoheck** [comment]
The spacing was used to understand the file as I edited in sublime text. It was easy to understand in that way. This doesn't affect who opens it in libreoffice for example.

**Pull request closed without merging**
