### PR TITLE
Fix pushbullet not being detected

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Well the issue was that Pushbullet was having a space bettween Icon=Name, i just add a regex pattern to ignore this space
tested it with pushbullet & my weather indicator, everything works fine

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Can you take a look at this @Foggalong if you have any free time of course!

**Comment by Foggalong** [comment]
Isn't `\s*` regex for any whitespace chr?

**Comment by bil-elmoussaoui** [comment]
`\s*`is for any whitespace chr and if there's no whitespace just ignore

**Comment by Foggalong** [comment]
Tested and all seems fine. Thanks for the fix!

**Comment by bil-elmoussaoui** [comment]
You're welcome!

**Pull request merged**
