### PR TITLE
Add telegram

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
Fixes the hardcoded icon of telegram desktop ,it's created in ```$HOME/.local/share/telegramdesktop.desktop```

### CODE REVIEW

**Comment by Foggalong** [comment]
Does using `$HOME` in that line work? I've previously rejected hardcoded apps with icons located in $HOME because we couldn't fix them :/

**Comment by bil-elmoussaoui** [comment]
I've no idea, i found an other icon using ```$HOME``` and i used it too, i might fix that if you want to?

**Comment by bil-elmoussaoui** [comment]
@Foggalong Can you take a look at what i changed in ```fix.sh```, The script keeps downloading a newer version :P I add this ```[home]``` in ```tofix.csv``` whenever you want to use the home directory, and replaced it in the script later

**Comment by Foggalong** [comment]
Well I don't know, I could be wrong! I've never had an app hardcoded in `$HOME` to be able to test so it could be having `$HOME` in the CSV file is a perfectly okay way to do it

**Comment by bil-elmoussaoui** [comment]
I don't think it's working. I tried this by doing ``` echo $current```, i will update this PR as soon as i finish my last exams

**Comment by bil-elmoussaoui** [comment]
There's some merge conflicts on this, i will reopen a new one as soon as possible

**Pull request closed without merging**
